EXEC sp_rename 'ProductFacetValueType', 'OfferingFacetValueType';
EXEC sp_rename 'PersonalListProducts', 'PersonalListOfferings';
EXEC sp_rename 'ProductOptionTypes', 'OfferingOptionTypes';
EXEC sp_rename 'ProductAttributes', 'OfferingAttributes';
EXEC sp_rename 'PromotionProducts', 'PromotionOfferings';
EXEC sp_rename 'Enum_ProductCodeType_NI', 'Enum_OfferingCodeType_NI';
EXEC sp_rename 'CompanyProductFacetValueType', 'CompanyOfferingFacetValueType';
EXEC sp_rename 'CommunityProducts', 'CommunityOfferings';
EXEC sp_rename 'Enum_ProductCondition_NI', 'Enum_OfferingCondition_NI';
EXEC sp_rename 'MarketplaceProducts', 'MarketplaceOfferings';
EXEC sp_rename 'Enum_ProductRejectReason', 'Enum_OfferingRejectReason';
EXEC sp_rename 'Enum_ProductStatus', 'Enum_OfferingStatus';
EXEC sp_rename 'Log_AdminProductReviews', 'Log_AdminOfferingReviews';
EXEC sp_rename 'ProductMaster', 'OfferingMaster';
EXEC sp_rename 'Enum_AdminProductReviewAction', 'Enum_AdminOfferingReviewAction';
EXEC sp_rename 'CommunityProductMessages', 'CommunityOfferingMessages';
EXEC sp_rename 'Enum_ProductPendingStatus', 'Enum_OfferingPendingStatus';
EXEC sp_rename 'Audit_ProductMaster_NI', 'Audit_OfferingMaster_NI';
EXEC sp_rename 'ProductLocations', 'OfferingLocations';
EXEC sp_rename 'ProductTags', 'OfferingTags';
EXEC sp_rename 'ProductCodes_NI', 'OfferingCodes_NI';
EXEC sp_rename 'ProductPriceTypes', 'OfferingPriceTypes';
EXEC sp_rename 'Enum_ProductOptionPriceType', 'Enum_OfferingOptionPriceType';
EXEC sp_rename 'ProductTagDetails', 'OfferingTagDetails';
EXEC sp_rename 'ProductOptionDetails', 'OfferingOptionDetails';
EXEC sp_rename 'ProductOptions', 'OfferingOptions';
EXEC sp_rename 'Log_AdminOfferingReviews.Product', 'Offering', 'COLUMN';
EXEC sp_rename 'OfferingTagDetails.Product', 'Offering', 'COLUMN';
EXEC sp_rename 'OfferingTags.Product', 'Offering', 'COLUMN';
EXEC sp_rename '__EFMigrationsHistory.ProductVersion', 'OfferingVersion', 'COLUMN';
EXEC sp_rename 'Categories.ProductType', 'OfferingType', 'COLUMN';
EXEC sp_rename 'PromotionOfferings.Product', 'Offering', 'COLUMN';
EXEC sp_rename 'CommunityOfferingMessages.CommunityProduct', 'CommunityOffering', 'COLUMN';
EXEC sp_rename 'Reviews.Product', 'Offering', 'COLUMN';
EXEC sp_rename 'OfferingCodes_NI.Product', 'Offering', 'COLUMN';
EXEC sp_rename 'CommunityOfferings.Product', 'Offering', 'COLUMN';
EXEC sp_rename 'PersonalListOfferings.Product', 'Offering', 'COLUMN';
EXEC sp_rename 'Messages.Product', 'Offering', 'COLUMN';
EXEC sp_rename 'CompanyReviews.Product', 'Offering', 'COLUMN';
EXEC sp_rename 'OfferingOptionDetails.Product', 'Offering', 'COLUMN';
EXEC sp_rename 'OfferingAttributes.Product', 'Offering', 'COLUMN';
EXEC sp_rename 'OfferingLocations.Product', 'Offering', 'COLUMN';
EXEC sp_rename 'OfferingOptions.Product', 'Offering', 'COLUMN';
EXEC sp_rename 'CommunityCategories.ProductCount', 'OfferingCount', 'COLUMN';

