// <auto-generated />
using System;
using BizSrt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace BizSrt.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BizSrt.Data.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Company")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte?>("ExternalProvider")
                        .HasColumnType("tinyint");

                    b.Property<byte>("InvalidLogonCount")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Options")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PendingStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("PwdHash")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("binary(24)")
                        .IsFixedLength();

                    b.Property<byte[]>("PwdSalt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("binary(24)")
                        .IsFixedLength();

                    b.Property<byte>("SecurityProfile")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.AreaName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AreaNames");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.Category", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<long>("Industry")
                        .HasColumnType("bigint");

                    b.Property<string>("Keywords")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NAICSCode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("OfferingType")
                        .HasColumnType("smallint");

                    b.Property<short?>("Parent")
                        .HasColumnType("smallint");

                    b.Property<short?>("QualifyingParent")
                        .HasColumnType("smallint");

                    b.Property<long>("ServiceType")
                        .HasColumnType("bigint");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("tinyint");

                    b.Property<short>("TransactionType")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CategoryOfferingAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Category")
                        .HasColumnType("smallint");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Requirement")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<string>("ValueOptions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoryOfferingAttributes");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.Category_Unwound", b =>
                {
                    b.Property<short>("Parent")
                        .HasColumnType("smallint");

                    b.Property<short>("Child")
                        .HasColumnType("smallint");

                    b.Property<bool>("HasChildren")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Parent", "Child");

                    b.ToTable("Categories_Unwound");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.Community", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Alias")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<string>("DefaultCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Geometry>("GeoLocation")
                        .HasColumnType("geography");

                    b.Property<int?>("Location")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Options")
                        .HasColumnType("tinyint");

                    b.Property<int>("Owner")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RichText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StreetName")
                        .HasColumnType("int");

                    b.Property<string>("StreetNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CommunityMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Community")
                        .HasColumnType("int");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Metadata")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varbinary(1000)");

                    b.Property<byte>("Order")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("CommunityMedia");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyAffiliation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<bool>("Declined")
                        .HasColumnType("bit");

                    b.Property<int>("From")
                        .HasColumnType("int");

                    b.Property<bool>("Pending")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("To")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CompanyAffiliations");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyCommunity", b =>
                {
                    b.Property<int>("Company")
                        .HasColumnType("int");

                    b.Property<int>("Community")
                        .HasColumnType("int");

                    b.Property<byte>("UnlistedType")
                        .HasColumnType("tinyint");

                    b.HasKey("Company", "Community");

                    b.ToTable("CompanyCommunities");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyFacet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Company")
                        .HasColumnType("int");

                    b.Property<int>("FacetValue")
                        .HasColumnType("int");

                    b.Property<bool>("UserDefined")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CompanyFacets");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyFacetName", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyFacetNames");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyFacetSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("InclFacets")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("Indexed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUsed")
                        .HasColumnType("datetime2");

                    b.Property<int>("UseCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CompanyFacetSets");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyFacetSetDetail", b =>
                {
                    b.Property<bool>("Exclude")
                        .HasColumnType("bit");

                    b.Property<int>("Set")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasIndex("Set");

                    b.ToTable("CompanyFacetSetDetails");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyFacetValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Name")
                        .HasColumnType("smallint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Value")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte>("ValueType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("CompanyFacetValues");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Company")
                        .HasColumnType("int");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Metadata")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varbinary(1000)");

                    b.Property<byte>("Order")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("CompanyMedia");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyOffering", b =>
                {
                    b.Property<long>("Offering")
                        .HasColumnType("bigint");

                    b.Property<string>("Alias")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("Category")
                        .HasColumnType("smallint");

                    b.Property<int>("Company")
                        .HasColumnType("int");

                    b.Property<byte>("ImportStatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("Indexed")
                        .HasColumnType("datetime");

                    b.Property<long?>("Industry")
                        .HasColumnType("bigint");

                    b.Property<long?>("ServiceType")
                        .HasColumnType("bigint");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("TransactionType")
                        .HasColumnType("smallint");

                    b.Property<byte>("UnlistedType")
                        .HasColumnType("tinyint");

                    b.HasKey("Offering");

                    b.ToTable("CompanyOfferings");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyOfferingFacet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("FacetValue")
                        .HasColumnType("int");

                    b.Property<long>("Offering")
                        .HasColumnType("bigint");

                    b.Property<bool>("UserDefined")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CompanyOfferingFacets");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyOfferingFacetName", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyOfferingFacetNames");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyOfferingFacetSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("InclFacets")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("Indexed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUsed")
                        .HasColumnType("datetime2");

                    b.Property<int>("UseCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CompanyOfferingFacetSets");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyOfferingFacetSetDetail", b =>
                {
                    b.Property<bool>("Exclude")
                        .HasColumnType("bit");

                    b.Property<int>("Set")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasIndex("Set");

                    b.ToTable("CompanyOfferingFacetSetDetails");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyOfferingFacetValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Name")
                        .HasColumnType("smallint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Value")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte>("ValueType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("CompanyOfferingFacetValues");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Company")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fax")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Geometry>("GeoLocation")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MetadataCheck")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte>("Order")
                        .HasColumnType("tinyint");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone1")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PlaceId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<short>("ProcessFlags")
                        .HasColumnType("smallint");

                    b.Property<int?>("StreetName")
                        .HasColumnType("int");

                    b.Property<string>("StreetNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("WebUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Company");

                    b.ToTable("CompanyOffices");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyOfficeId", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Office")
                        .HasColumnType("int");

                    b.ToTable("CompanyOfficeIds");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyOffice_Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Company")
                        .HasColumnType("int");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Latitude")
                        .HasColumnType("real");

                    b.Property<int?>("Location")
                        .HasColumnType("int");

                    b.Property<float?>("Longitude")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StreetName")
                        .HasColumnType("int");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyOffices_Audit");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("Category")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Indexed")
                        .HasColumnType("datetime");

                    b.Property<long>("Industry")
                        .HasColumnType("bigint");

                    b.Property<byte>("MembershipType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte>("Options")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PendingStatus")
                        .HasColumnType("tinyint");

                    b.Property<short>("ProcessFlags")
                        .HasColumnType("smallint");

                    b.Property<byte>("RejectReason")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RichText")
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("ServiceType")
                        .HasColumnType("bigint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("TransactionType")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("WebSite")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("CompanyProfiles");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyProject", b =>
                {
                    b.Property<long>("Project")
                        .HasColumnType("bigint");

                    b.Property<int>("Company")
                        .HasColumnType("int");

                    b.Property<byte>("UnlistedType")
                        .HasColumnType("tinyint");

                    b.HasKey("Project");

                    b.ToTable("CompanyProjects");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.Currency", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("CountryPriceFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISOCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.FacetSetCompany", b =>
                {
                    b.Property<int>("FacetSet")
                        .HasColumnType("int");

                    b.Property<int>("Company")
                        .HasColumnType("int");

                    b.HasKey("FacetSet", "Company");

                    b.ToTable("FacetSetCompanies");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.FacetSetCompanyOffering", b =>
                {
                    b.Property<int>("FacetSet")
                        .HasColumnType("int");

                    b.Property<long>("Offering")
                        .HasColumnType("bigint");

                    b.HasKey("FacetSet", "Offering");

                    b.ToTable("FacetSetCompanyOfferings");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.Industry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Industries");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.Job", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Company")
                        .HasColumnType("int");

                    b.Property<short>("Department")
                        .HasColumnType("smallint");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("Location")
                        .HasColumnType("int");

                    b.Property<int>("Organization")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("StreetName")
                        .HasColumnType("int");

                    b.Property<string>("StreetNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<byte>("UnlistedType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Parent")
                        .HasColumnType("int");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<bool>("UserDefined")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.Location_Unwound", b =>
                {
                    b.Property<int>("Parent")
                        .HasColumnType("int");

                    b.Property<int>("Child")
                        .HasColumnType("int");

                    b.HasKey("Parent", "Child");

                    b.ToTable("Locations_Unwound");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.Offering", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<long?>("Master")
                        .HasColumnType("bigint");

                    b.Property<byte>("PendingStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("RejectReason")
                        .HasColumnType("tinyint");

                    b.Property<string>("RichText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime");

                    b.Property<string>("WebUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Offerings");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.OfferingAttributeType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("EditorType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Primitive")
                        .HasColumnType("bit");

                    b.Property<string>("ValueOptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("ValueType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("OfferingAttributeTypes");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.OfferingIdKeyless", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.ToTable("OfferingIdsKeyless");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.OfferingMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Metadata")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varbinary(1000)");

                    b.Property<long>("Offering")
                        .HasColumnType("bigint");

                    b.Property<byte>("Order")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("OfferingMedia");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.OfferingType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OfferingTypes");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<short>("Category")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Indexed")
                        .HasColumnType("datetime");

                    b.Property<int?>("Location")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RichText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int?>("StreetName")
                        .HasColumnType("int");

                    b.Property<string>("StreetNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<byte>("TenderType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.ProjectIdKeyless", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.ToTable("ProjectIdsKeyless");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.ProjectMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Metadata")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varbinary(1000)");

                    b.Property<byte>("Order")
                        .HasColumnType("tinyint");

                    b.Property<long>("Project")
                        .HasColumnType("bigint");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("ProjectMedia");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("Company")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.SecurityProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentProfile")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SecurityProfiles");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.SecurityProfilePriviledge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Priviledge")
                        .HasColumnType("int");

                    b.Property<int>("Profile")
                        .HasColumnType("int");

                    b.Property<bool>("Restricted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SecurityProfilePriviledges");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.ServiceType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.StreetName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("City")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StreetNames");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.TransactionType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransactionTypes");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyFacetSetDetail", b =>
                {
                    b.HasOne("BizSrt.Data.Entities.CompanyFacetSet", "CompanyFacetSet")
                        .WithMany()
                        .HasForeignKey("Set")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyFacetSet");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyOffering", b =>
                {
                    b.HasOne("BizSrt.Data.Entities.Offering", "OfferingNavigation")
                        .WithOne()
                        .HasForeignKey("BizSrt.Data.Entities.CompanyOffering", "Offering")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfferingNavigation");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyOfferingFacetSetDetail", b =>
                {
                    b.HasOne("BizSrt.Data.Entities.CompanyOfferingFacetSet", "CompanyOfferingFacetSet")
                        .WithMany()
                        .HasForeignKey("Set")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyOfferingFacetSet");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyOffice", b =>
                {
                    b.HasOne("BizSrt.Data.Entities.CompanyProfile", "CompanyProfile")
                        .WithMany("Offices")
                        .HasForeignKey("Company")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyProfile");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyProject", b =>
                {
                    b.HasOne("BizSrt.Data.Entities.Project", "ProjectNavigation")
                        .WithOne()
                        .HasForeignKey("BizSrt.Data.Entities.CompanyProject", "Project")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectNavigation");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.Job", b =>
                {
                    b.HasOne("BizSrt.Data.Entities.Offering", "OfferingNavigation")
                        .WithOne()
                        .HasForeignKey("BizSrt.Data.Entities.Job", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfferingNavigation");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.Promotion", b =>
                {
                    b.HasOne("BizSrt.Data.Entities.Community", "CommunityNavigation")
                        .WithOne()
                        .HasForeignKey("BizSrt.Data.Entities.Promotion", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommunityNavigation");
                });

            modelBuilder.Entity("BizSrt.Data.Entities.CompanyProfile", b =>
                {
                    b.Navigation("Offices");
                });
#pragma warning restore 612, 618
        }
    }
}
