syntax = "proto3";

option csharp_namespace = "BizSrt.Model.Grpc";

package company;

service CompanyService {
  rpc IndexCompany (IndexCompanyRequest) returns (IndexCompanyResponse);
  rpc IndexOffering (IndexOfferingRequest) returns (IndexOfferingResponse);
  rpc IndexOfferingFacetSet (IndexOfferingFacetSetRequest) returns (IndexOfferingFacetSetResponse);
  rpc DeleteOfferingFacetSet (DeleteOfferingFacetSetRequest) returns (DeleteOfferingFacetSetResponse);
}

message IndexCompanyRequest {
  int32 company_id = 1;
}

message IndexCompanyResponse {
  bool success = 1;
}

message IndexOfferingRequest {
  int64 offering_id = 1;
}

message IndexOfferingResponse {
  bool success = 1;
}

message IndexOfferingFacetSetRequest {
  int32 set_id = 1;
}

message IndexOfferingFacetSetResponse {
  bool success = 1;
}

message DeleteOfferingFacetSetRequest {
  int32 set_id = 1;
}

message DeleteOfferingFacetSetResponse {
  bool success = 1;
}
